### ISSUE TITLE
TCP connection timeout

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1247] opened 2019-03-06 14:43 UTC
Similar to https://github.com/openshift/openshift-azure/issues/1102 but not quite

```
 read tcp 172.16.146.23:39556->52.188.220.61:443: read: connection timed out
```

``` 
time="2019-03-06T14:29:36Z" level=debug msg="400 Bad Request: Failed to apply request: WaitForNodes: Get https://e2e-ifjiialm.eastus.cloudapp.azure.com/api/v1/nodes/master-000000: read tcp 172.16.146.23:39556->52.188.220.61:443: read: connection timed out" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:12"
time="2019-03-06T14:29:36Z" level=fatal msg="containerservice.OpenShiftManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: error response cannot be parsed: \"400 Bad Request: Failed to apply request: WaitForNodes: Get https://e2e-ifjiialm.eastus.cloudapp.azure.com/api/v1/nodes/master-000000: read tcp 172.16.146.23:39556->52.188.220.61:443: read: connection timed out\\n\" error: json: cannot unmarshal number into Go value of type azure.RequestError"
```

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1178/pull-ci-openshift-openshift-azure-master-e2e-azure/2671

/kind test-flake

**Comment by jim-minter** [comment] 2019-03-15 16:04
calling this a duplicate of #1102

**Closed by jim-minter** 2019-03-15 16:04 UTC
Labels: kind/test-flake
