### ISSUE TITLE
Cannot query api server - connection timed out

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#560] opened 2018-10-05 08:22 UTC
Failure to complete setup of e2e tests

```
+ az group create -n ci-op-s6k78vy0-3b9ab -l eastus --tags now=1538581995 ttl=76h
+ set +x
+ cat
+ go generate ./...
bindata.go
bindata.go
+ go run cmd/createorupdate/createorupdate.go -loglevel=debug
time="2018-10-03T15:53:29Z" level=info msg="convert to internal" resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T15:53:29Z" level=info msg=enrich resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T15:53:29Z" level=info msg="validating internal data models" resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T15:53:29Z" level=info msg="generating configs" resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T15:53:38Z" level=info msg="persist config" resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T15:53:38Z" level=info msg="generating arm templates" resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T15:53:38Z" level=info msg="write helpers" resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T15:53:38Z" level=info msg="applying arm template deployment" resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T15:53:40Z" level=info msg="waiting for arm template deployment to complete" resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T15:58:40Z" level=info msg="initializing cluster" resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T15:58:41Z" level=info msg="starting health check" resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T15:59:47Z" level=info msg="waiting for master-000000 to be ready" resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T16:03:55Z" level=info msg="waiting for master-000001 to be ready" resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T16:03:57Z" level=info msg="waiting for master-000002 to be ready" resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T16:03:57Z" level=info msg="waiting for infra-000000 to be ready" resourceGroup=ci-op-s6k78vy0-3b9ab
time="2018-10-03T16:20:34Z" level=fatal msg="Get https://ci-op-s6k78vy0-3b9ab.eastus.cloudapp.azure.com/api/v1/nodes/infra-000000: read tcp 172.16.63.58:45078->40.87.90.62:443: read: connection timed out"
exit status 1
2018/10/03 16:20:35 Container setup in pod e2e-azure-upgrade failed, exit code 1, reason Error
2018/10/03 16:20:40 Container test in pod e2e-azure-upgrade failed, exit code 1, reason Error
2018/10/03 16:26:31 Container teardown in pod e2e-azure-upgrade completed successfully
2018/10/03 16:26:31 Copying artifacts from e2e-azure-upgrade into /logs/artifacts/e2e-azure-upgrade
2018/10/03 16:26:32 Copied 17.10Mi of artifacts from e2e-azure-upgrade to /logs/artifacts/e2e-azure-upgrade
2018/10/03 16:26:37 Ran for 38m48s
error: could not run steps: could not wait for pod to complete: could not wait for pod completion: the pod ci-op-s6k78vy0/e2e-azure-upgrade failed after 33m24s (failed containers: setup, test):  unknown

Container setup exited with code 1, reason Error
Container test exited with code 1, reason Error
```

https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/logs/branch-ci-openshift-openshift-azure-master-e2e-azure-upgrade/24/

/kind test-flake

**Comment by kargakis** [comment] 2018-10-08 11:02
Please post the artifacts for this job to better triage.

**Comment by charlesakalugwu** [comment] 2018-10-08 11:13
updated with link to artifacts

**Comment by kargakis** [comment] 2018-10-08 11:15
So trying to get the infra node from the k8s api times out but the deployment eventually succeeds (all nodes and pods are up and running).

**Comment by kargakis** [comment] 2018-10-11 15:37
And another one https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/593/pull-ci-openshift-openshift-azure-master-e2e-azure/250/build-log.txt

**Comment by kargakis** [comment] 2019-01-07 12:02
Another one: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/981/pull-ci-openshift-openshift-azure-master-e2e-azure/1730

On the client:
```
time="2019-01-07T11:17:33Z" level=info msg="checking deployment default/docker-registry"
time="2019-01-07T11:34:01Z" level=debug msg="400 Bad Request: Failed to apply request: WaitForInfraDeployments: Get https://e2e-rsneaihx.eastus.cloudapp.azure.com/apis/apps/v1/namespaces/default/deployments/docker-registry: read tcp 172.16.101.209:32884->104.45.186.64:443: read: connection timed out"
```
On the api server, it seems that all requests to the registry deployment endpoint are successful from the time the initial request is made:
```
17155:I0107 11:17:33.419119       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.024691ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17166:I0107 11:17:34.441095       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (2.896787ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17169:I0107 11:17:35.442442       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.976219ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17181:I0107 11:17:36.441487       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.249798ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17196:I0107 11:17:37.511896       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (73.410709ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17207:I0107 11:17:37.667006       1 wrap.go:42] PUT /apis/apps/v1/namespaces/default/deployments/docker-registry/status: (43.587612ms) 200 [[openshift/v1.11.0+d4cacc0 (linux/amd64) kubernetes/d4cacc0/system:serviceaccount:kube-system:deployment-controller] 10.0.0.6:46654]
17213:I0107 11:17:38.442944       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (4.165625ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17256:I0107 11:17:39.443149       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (4.740943ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17301:I0107 11:17:40.441973       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.641809ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17308:I0107 11:17:41.442126       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.631909ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17354:I0107 11:17:42.442455       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.841415ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17360:I0107 11:17:43.442365       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.796515ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17416:I0107 11:17:44.442018       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.437303ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17464:I0107 11:17:45.441945       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.291699ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17478:I0107 11:17:46.499307       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (60.619124ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17484:I0107 11:17:47.442344       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.707412ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17487:I0107 11:17:48.442208       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.613008ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17495:I0107 11:17:49.449050       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (10.240508ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17507:I0107 11:17:50.442021       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.278199ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17512:I0107 11:17:51.442003       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.386502ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17558:I0107 11:17:52.442246       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.422503ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17567:I0107 11:17:53.452129       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (13.320401ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17573:I0107 11:17:54.442091       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.375802ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17587:I0107 11:17:55.442266       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.488605ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17602:I0107 11:17:56.442173       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.378102ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17605:I0107 11:17:57.442925       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.718312ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17609:I0107 11:17:58.442767       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.841715ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17624:I0107 11:17:59.443675       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (4.768544ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17707:I0107 11:18:00.444580       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (5.186456ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17720:I0107 11:18:01.442140       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.178896ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17768:I0107 11:18:02.443234       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.559207ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17788:I0107 11:18:05.209058       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (6.397492ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17789:I0107 11:18:05.442358       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.451204ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17797:I0107 11:18:06.442909       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.838916ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17809:I0107 11:18:07.449184       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (10.235808ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17816:I0107 11:18:08.442995       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.844115ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17903:I0107 11:18:09.732661       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (48.599162ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
17908:I0107 11:18:10.441897       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (2.846786ms) 200 [[main/v0.0.0 (linux/amd64) kubernetes/$Format] 35.243.216.181:32884]
18812:I0107 11:18:35.365446       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (9.304069ms) 200 [[sync/v0.0.0 (linux/amd64) kubernetes/$Format] 40.90.228.16:39420]
19547:I0107 11:18:45.507135       1 wrap.go:42] PUT /apis/apps/v1/namespaces/default/deployments/docker-registry/status: (24.690082ms) 200 [[openshift/v1.11.0+d4cacc0 (linux/amd64) kubernetes/d4cacc0/system:serviceaccount:kube-system:deployment-controller] 10.0.0.6:46654]
24143:I0107 11:21:43.499020       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.175715ms) 200 [[sync/v0.0.0 (linux/amd64) kubernetes/$Format] 40.90.228.16:39420]
29099:I0107 11:24:49.441062       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.144215ms) 200 [[sync/v0.0.0 (linux/amd64) kubernetes/$Format] 40.90.228.16:39420]
34260:I0107 11:27:55.198685       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (2.950814ms) 200 [[sync/v0.0.0 (linux/amd64) kubernetes/$Format] 40.90.228.16:39420]
39550:I0107 11:31:00.987264       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.102014ms) 200 [[sync/v0.0.0 (linux/amd64) kubernetes/$Format] 40.90.228.16:39420]
44336:I0107 11:34:07.197715       1 wrap.go:42] GET /apis/apps/v1/namespaces/default/deployments/docker-registry: (3.509916ms) 200 [[sync/v0.0.0 (linux/amd64) kubernetes/$Format] 40.90.228.16:39420]
```
@amanohar can you track down this request in the `ci-op-3dbq9nhp` resource group?

**Comment by jim-minter** [comment] 2019-01-11 00:13
I think that `read: connection timed out` means that the TCP socket send buffer still holds outgoing data (written by the HTTP client) which it has being trying to send to the server for some time, but which the server has not acknowledged.

The client is trying to read the HTTP response from the socket, and the local TCP stack injects an error because it is timing out the send (and the read is never going to succeed).  In all of the examples of this issue that I've seen, the timeout is about 17 minutes.  See tcp(7), tcp_retries2 for more information.

I've been able to simulate this happening with iptables rules.

The log above is interesting, but the PUT calls against /status by the deployment controller and the GET calls by the sync pod should be ignored.

What this then shows is that "checking deployment" checked every second (as it should) from 11:17:33 to 11:18:10.  From then on no requests are received by the server, and at 11:34:01 we know the client gave up.

I think something went badly wrong with the client TCP connection around 11:18:10 which meant that effectively the client and server were completely isolated from then onwards.  Now, the question is, what happened?

**Comment by jim-minter** [comment] 2019-01-11 14:19
@openshift/sig-azure @sozercan it would be extremely useful to confirm with this issue: is it something that we've seen only in our CI, or do we see it outside of our CI as well?

**Comment by kargakis** [comment] 2019-01-15 11:14
> @openshift/sig-azure @sozercan it would be extremely useful to confirm with this issue: is it something that we've seen only in our CI, or do we see it outside of our CI as well?

Running the etcd restore e2e test in a bash loop from my machine to try to reproduce locally.
```sh
while true; do make e2e-etcdbackuprecovery; return=$?; if [[ $return != "0" ]]; then exit $return; fi; done
```

**Comment by kargakis** [comment] 2019-01-16 09:33
Opened https://github.com/openshift/release/issues/2608 in the release repo so we can get the CI folks involved.

**Comment by Makdaam** [comment] 2019-01-16 14:04
Recent one https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1042/pull-ci-openshift-openshift-azure-master-e2e-azure/1913

**Comment by jim-minter** [comment] 2019-01-16 18:57
#1050 switches on enableTCPReset - see https://docs.microsoft.com/en-US/azure/load-balancer/load-balancer-tcp-reset for more info

**Comment by Makdaam** [comment] 2019-01-18 11:40
another flake https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1043/pull-ci-openshift-openshift-azure-master-e2e-azure/1996

Timeline reference: #1050 is not merged yet.

**Comment by Makdaam** [comment] 2019-01-29 14:24
https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/branch-ci-openshift-openshift-azure-master-e2e-azure/131/

**Comment by Makdaam** [comment] 2019-01-29 14:24
Flakes after #1050 merged, seems to be CI env issue.

**Comment by mjudeikis** [comment] 2019-02-18 11:18
close. Should be solved by https://github.com/openshift/openshift-azure/blob/master/pkg/cluster/kubeclient/types.go#L52

**Closed by mjudeikis** 2019-02-18 11:18 UTC
Labels: kind/test-flake
