### ISSUE TITLE
Timeout waiting for master-000000 to be ready

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#1356] opened 2019-03-26 21:11 UTC
Sometimes we see the following errors"

```
time="2019-03-26T13:41:22Z" level=info msg="draining master-000000" func="github.com/openshift/openshift-azure/pkg/cluster.(*simpleUpgrader).UpdateMasterAgentPool" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/update_master.go:38"
time="2019-03-26T13:41:22Z" level=info msg="deallocating master-000000" func="github.com/openshift/openshift-azure/pkg/cluster.(*simpleUpgrader).UpdateMasterAgentPool" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/update_master.go:44"
time="2019-03-26T13:44:37Z" level=info msg="updating master-000000" func="github.com/openshift/openshift-azure/pkg/cluster.(*simpleUpgrader).UpdateMasterAgentPool" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/update_master.go:50"
time="2019-03-26T13:45:09Z" level=info msg="reimaging master-000000" func="github.com/openshift/openshift-azure/pkg/cluster.(*simpleUpgrader).UpdateMasterAgentPool" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/update_master.go:58"
time="2019-03-26T13:45:40Z" level=info msg="starting master-000000" func="github.com/openshift/openshift-azure/pkg/cluster.(*simpleUpgrader).UpdateMasterAgentPool" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/update_master.go:64"
time="2019-03-26T13:47:44Z" level=info msg="waiting for master-000000 to be ready" func="github.com/openshift/openshift-azure/pkg/cluster.(*simpleUpgrader).UpdateMasterAgentPool" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/update_master.go:70"
time="2019-03-26T13:47:54Z" level=warning msg="dial tcp 104.45.65.206:443: i/o timeout: retry 1" func="github.com/openshift/openshift-azure/pkg/cluster/kubeclient.(*retryingRoundTripper).RoundTrip" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/kubeclient/roundtrip.go:102"
time="2019-03-26T13:48:04Z" level=warning msg="dial tcp 104.45.65.206:443: i/o timeout: retry 2" func="github.com/openshift/openshift-azure/pkg/cluster/kubeclient.(*retryingRoundTripper).RoundTrip" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/kubeclient/roundtrip.go:102"
time="2019-03-26T13:48:14Z" level=warning msg="dial tcp 104.45.65.206:443: i/o timeout: retry 3" func="github.com/openshift/openshift-azure/pkg/cluster/kubeclient.(*retryingRoundTripper).RoundTrip" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/kubeclient/roundtrip.go:102"
time="2019-03-26T13:48:24Z" level=warning msg="dial tcp 104.45.65.206:443: i/o timeout: retry 4" func="github.com/openshift/openshift-azure/pkg/cluster/kubeclient.(*retryingRoundTripper).RoundTrip" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/kubeclient/roundtrip.go:102"
time="2019-03-26T13:48:34Z" level=warning msg="dial tcp 104.45.65.206:443: i/o timeout: retry 5" func="github.com/openshift/openshift-azure/pkg/cluster/kubeclient.(*retryingRoundTripper).RoundTrip" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/kubeclient/roundtrip.go:102"
time="2019-03-26T13:48:44Z" level=warning msg="&net.OpError{Op:\"dial\", Net:\"tcp\", Source:net.Addr(nil), Addr:(*net.TCPAddr)(0xc0008f0720), Err:(*poll.TimeoutError)(0x2ab7840)}: not retrying" func="github.com/openshift/openshift-azure/pkg/cluster/kubeclient.(*retryingRoundTripper).RoundTrip" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/kubeclient/roundtrip.go:118"
time="2019-03-26T13:48:44Z" level=debug msg="400 Bad Request: Failed to apply request: UpdateMasterAgentPoolWaitForReady: Get https://dhfkcytwsbdiqmngvlsf.westeurope.cloudapp.azure.com/api/v1/nodes/master-000000: dial tcp 104.45.65.206:443: i/o timeout" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:11"
time="2019-03-26T13:48:44Z" level=debug msg="ending:   PUT /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/upgrade-gnxexh/providers/Microsoft.ContainerService/openShiftManagedClusters/upgrade-gnxexh?api-version=2018-09-30-preview" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).logger.func1" file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/middleware.go:15"
time="2019-03-26T13:48:44Z" level=fatal msg="containerservice.OpenShiftManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: error response cannot be parsed: \"400 Bad Request: Failed to apply request: UpdateMasterAgentPoolWaitForReady: Get https://dhfkcytwsbdiqmngvlsf.westeurope.cloudapp.azure.com/api/v1/nodes/master-000000: dial tcp 104.45.65.206:443: i/o timeout\\n\" error: json: cannot unmarshal number into Go value of type azure.RequestError"
exit status 1
+ return_id=1
+ set +ex
signal: terminated
make: *** [upgrade] Error 1
```

sample artifacts: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1349/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/15/

/kind test-flake

**Comment by jim-minter** [comment] 2019-03-26 21:13
duplicate of #1102

**Closed by jim-minter** 2019-03-26 21:13 UTC
Labels: kind/test-flake
