### ISSUE TITLE
fake rp server not starting

### ISSUE THREAD

**Issue by asalkeld** [openshift/openshift-azure#1617] opened 2019-05-03 06:24 UTC
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1583/pull-ci-azure-master-upgrade-v5.0/14

```
./hack/create.sh ci-1583-e2e-upgrade-umtbdc
time="2019-05-02T08:25:01Z" level=info msg="using region northeurope"
time="2019-05-02T08:25:01Z" level=info msg="ensuring resource group ci-1583-e2e-upgrade-umtbdc"
time="2019-05-02T08:26:04Z" level=fatal msg="timed out waiting for the condition"
exit status 1
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
time="2019-05-02T08:26:10Z" level=info msg="starting the fake resource provider" func=main.main file="/tmp/tmp.6kMNo70TBC/src/github.com/openshift/openshift-azure/cmd/fakerp/main.go:20"
time="2019-05-02T08:26:10Z" level=info msg="validating external plugin api data models" func="github.com/openshift/openshift-azure/pkg/plugin.(*plugin).ValidatePluginTemplate" file="/tmp/tmp.6kMNo70TBC/src/github.com/openshift/openshift-azure/pkg/plugin/plugin.go:86"
time="2019-05-02T08:26:10Z" level=info msg="starting server on localhost:8080" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).Run" file="/tmp/tmp.6kMNo70TBC/src/github.com/openshift/openshift-azure/pkg/fakerp/server.go:69"
{"component":"entrypoint","level":"error","msg":"Process did not finish before 4h0m0s timeout","time":"2019-05-02T12:20:39Z"}
{"component":"entrypoint","level":"error","msg":"Process did not exit before 15s grace period","time":"2019-05-02T12:20:54Z"}
```

/kind test-flake

**Comment by Makdaam** [comment] 2019-05-06 09:05
same in
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1471/pull-ci-azure-master-e2e-create/139
and
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1471/pull-ci-azure-master-upgrade-v5.0/16

**Comment by ehashman** [comment] 2019-07-29 20:16
I think this is not the fakerp server failing to start but rather the RG failing to create preventing the fakerp from starting. We might either want to add retry logic to RG creation or fail CI sooner.

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1796/pull-ci-azure-master-upgrade-v5.1/505/build-log.txt #1796 
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1819/pull-ci-azure-master-upgrade-v5.1/503/build-log.txt #1819

**Comment by ehashman** [comment] 2019-09-25 21:12
Dupe of #1628. Closing

**Closed by ehashman** 2019-09-25 21:12 UTC
Labels: kind/test-flake
