### ISSUE TITLE
Stop AAD reusability

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1112] opened 2019-02-06 11:42 UTC
RealRP creates AAD applications each time it provisions new cluster (not counting usecases when the user brings already provisioned AAD app).
We should stop re-use `user-name-aad` applications and make sure we create a new test-aad application for each cluster as part of fakeRP flow and delete it after the cluster is deleted

Currently, https://github.com/openshift/openshift-azure/pull/902 is pending to merge because "old" @asalkeld application behaves differently compared to newly created apps with same permissions. This implies that aad applications, provisioned using old and new API can behave differently. 

We still in progress of debugging what happening, but as soon as PR is closed we should consider moving to stop reusing AAD apps.

@jim-minter @charlesakalugwu

**Comment by jim-minter** [comment] 2019-05-01 01:26
We now provision service principals in the fake rp for everything except the AAD OIDC integration (this matches the real rp).
This carries a certain amount of risk: the root SP that provisions the temp SPs is moderately powerful, and we don't want its credentials to leak.

Theoretically it would be nice if we auto-provisioned the AAD OIDC SP as well, but the problem is that we would need the root SP to admin authorise the temp SP.  At that point the root SP would become more powerful than I'm comfortable with.  On that basis I propose closing this.

**Closed by jim-minter** 2019-05-01 01:26 UTC
Labels: kind/cleanup
