### ISSUE TITLE
Consider marking nodes as unschedulable during upgrade

### ISSUE THREAD

**Issue by kwoodson** [openshift/openshift-azure#269] opened 2018-08-27 15:35 UTC
By marking nodes as unschedulable during upgrades we will minimize the churn of applications, pvs, etc.

**Comment by kargakis** [comment] 2018-08-27 17:01
Mark all nodes as unschedulable or only old? Shouldn't the scheduler optimize by using the new node to schedule pods evicted from an old node vs spreading across other old nodes (which makes this a scheduler problem and not ours)?

**Comment by kwoodson** [comment] 2018-08-27 18:34
@kargakis, I was referring to old nodes.  The scheduler should handle this case if at all possible to minimize churn.  We've had issues in the past where pvs will get stuck on nodes and unable to detach.  My attempt here was to bring this to our attention and minimize churn if at all possible.

**Comment by kargakis** [comment] 2018-08-30 11:13
The problem with PVs is definitely an issue of the scheduler. Not sure it is worked around by marking old nodes as unschedulable.

**Comment by jim-minter** [comment] 2018-09-03 18:17
@kwoodson I don't understand what this issue is getting at - please can you update or close?

**Comment by kwoodson** [comment] 2018-09-03 19:26
The issue is that we could potentially have rotating applications during the upgrade process. In our dedicated or online environments, this has been a problem and can be mitigated by attempting to set old nodes to unscheduable.

**Comment by jim-minter** [comment] 2018-09-03 19:53
I still don't understand :(
Currently for each infra/compute node, we repeatedly:
* spin up new node, wait for ready
* set unschedulable on an old node, drain old node, delete old node

What is this issue aiming to change?

**Comment by kargakis** [comment] 2018-09-04 06:14
The issue is about avoiding scheduling pods that were evicted from an old
node to a different old node that is yet to get upgraded to avoid evicting
the same pod more than once during an upgrade.

**Comment by kwoodson** [comment] 2018-09-06 19:15
@jim-minter, @kargakis, if you feel the scheduler is intelligent enough to do this then feel free to close.  We can always revisit if customers feel this is causing issues with deployments.

**Comment by jim-minter** [comment] 2018-09-13 00:59
@kwoodson I think this belongs upstream - something like a hint on eviction that says, "hey, scheduler, there's an empty node the same size over there".  Please could you follow up upstream and close this?

**Comment by kwoodson** [comment] 2018-09-13 14:35
@jim-minter, I had a quick IRC conversation with @aveshagarwal.
```
avesh, during upgrades we add new nodes.  What is the behavior of the scheduler?  We want to minimize pod churn during upgrades.

kwoodson, should not matter if nodes are old or new, so scheduler will start seeing more nodes (old nodes and new nodes) and will schedule accordingly

avesh, does it prioritize the newer nodes higher than old nodes?  We'd prefer to minimize pod churn as well as pvs getting moved.
kwoodson, no

avesh, is it valuable to us to mark old nodes as unschedulable during an upgrade?
kwoodson, you would set old nodes as unschedulable if you dont want the scheduler to schedule there obviously, but what are you trying to solve here?

avesh, In our environments we want to minimize pod churn as well as PV churn.  If a pod moves from each node in a cluster each time it is evacuated and drained this could cause issues.

kwoodson, after a pod is evicted, the new replacement pod could be scheduled anywhere on schedulable nodes depending upon the pod's requirements, so there is no such guarantee that the new replacement pod would stick to the same node
```

It seems as though there is nothing special in the scheduler to avoid the behavior of skipping old nodes to minimize the churn.  According to the scheduler docs https://docs.openshift.com/container-platform/3.10/admin_guide/scheduling/scheduler.html, the nodes are placed into a prioritized list of possible candidates to accept the pod.  AFAICS, I did not find anything that prioritizes new nodes higher than existing nodes.

@aveshagarwal, is there a way to do this prioritization in the scheduler?  Is it worth us opening an issue upstream to influence the scheduler in this manner?  Thanks in advance.

**Comment by aveshagarwal** [comment] 2018-09-13 14:53
> The issue is about avoiding scheduling pods that were evicted from an old
node to a different old node that is yet to get upgraded to avoid evicting
the same pod more than once during an upgrade.

That could be solved by setting old, yet-to-upgraded-nodes as unschedulable (either by specifically setting unschedulable or by tainting the nodes with a taint).

**Comment by aveshagarwal** [comment] 2018-09-13 14:54
> @kwoodson re online, any idea why the scheduler would pick an old node
(that presumably has more running workload) instead of a new node? I

Scheduler already does that and in general picks nodes with less load for even spreading.

**Comment by aveshagarwal** [comment] 2018-09-13 14:56
> @kwoodson I think this belongs upstream - something like a hint on eviction that says, "hey, scheduler, there's an empty node the same size over there". Please could you follow up upstream?

Scheduler already does that, so if among all schedulable, lets say the pod being scheduled can be scheduled on 5 nodes, the scheduler would pick the one with less load from those 5 nodes.

**Comment by kargakis** [comment] 2018-09-13 14:57
> Scheduler already does that and in general picks nodes with less load for even spreading.

Do you use surge nodes in online or upgrade are done in place?

**Comment by kwoodson** [comment] 2018-09-13 17:34
@aveshagarwal, thanks for the comments.

They are using scale groups now.  This means that there is completely new capacity.  So old scale group and new scale group exist.  On old scale group, we mark all nodes as unschedulable, bring up new scale group, call evacuate/drain, and then kill the old scale group.

**Comment by aveshagarwal** [comment] 2018-09-13 17:41
> @aveshagarwal, thanks for the comments.

> They are using scale groups now. This means that there is completely new capacity. So old scale group and new scale group exist. On old scale group, we mark all nodes as unschedulable, bring up new scale group, call evacuate/drain, and then kill the old scale group.

That sounds good. So what is the issue?

**Comment by kwoodson** [comment] 2018-09-13 17:50
@aveshagarwal, this was directed @kargakis.  There isn't an issue in online because it matches capacity and begins the upgrade process.

The question in our upgrade strategy is that we replace node-by-node.  Bring up new node, unschedulable/drain old node, shut down old node.  From your earlier description, it sounds like this method will be okay because of the cpu load on the newer machines will theoretically be lower than the existing nodes and therefore the scheduler should choose those nodes instead of old nodes yet to be upgraded.

We can keep an eye on this post PP.  I'm satisfied with this answer for now.

**Closed** 2018-09-13 17:50 UTC
Labels: enhancement
