### ISSUE TITLE
sync pod test "should not continuously update objects" fails

### ISSUE THREAD

**Issue by thekad** [openshift/openshift-azure#1839] opened 2019-08-09 03:25 UTC
Hadn't seen this error before, not sure if transient in #1838 

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1838/pull-ci-azure-master-e2e-create/767

**Comment by m1kola** [comment] 2019-08-09 08:59
Seen it in #1836 

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1836/pull-ci-azure-master-e2e-create/772/build-log.txt

**Comment by charlesakalugwu** [comment] 2019-08-16 06:48
this is a duplicate of #1778 
/close

**Closed by charlesakalugwu** 2019-08-16 06:48 UTC
