### ISSUE TITLE
  should start kube-state-metrics correctly

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#850] opened 2018-12-06 08:47 UTC
```
Openshift on Azure admin e2e tests [AzureClusterReader] 
  should start kube-state-metrics correctly
  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/admin.go:66
panic: test timed out after 20m0s

goroutine 637 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1296 +0xfd
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44

goroutine 1 [chan receive, 20 minutes]:
testing.(*T).Run(0xc00017eb00, 0x12a6d92, 0x7, 0x1335028, 0x481296)
	/usr/local/go/src/testing/testing.go:879 +0x37a
testing.runTests.func1(0xc00017ea00)
	/usr/local/go/src/testing/testing.go:1119 +0x78
testing.tRunner(0xc00017ea00, 0xc0004d3e08)
	/usr/local/go/src/testing/testing.go:827 +0xbf
testing.runTests(0xc000186980, 0x1f793e0, 0x1, 0x1, 0x40d8df)
	/usr/local/go/src/testing/testing.go:1117 +0x2aa
testing.(*M).Run(0xc000160180, 0x0)
	/usr/local/go/src/testing/testing.go:1034 +0x165
main.main()
	_testmain.go:42 +0x13d

goroutine 5 [syscall, 20 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 6 [chan receive]:
github.com/openshift/openshift-azure/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1fa05c0)
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/golang/glog/glog.go:879 +0x8b
created by github.com/openshift/openshift-azure/vendor/github.com/golang/glog.init.0
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 12 [chan receive]:
github.com/openshift/openshift-azure/vendor/k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc0004ad0a0, 0xc000413890, 0xc0004ee120, 0x85833d, 0x11b1600)
	/go/src/github.com/openshift/openshift-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:310 +0x58
github.com/openshift/openshift-azure/vendor/k8s.io/apimachinery/pkg/util/wait.pollInternal(0xc0004ad0a0, 0xc000413890, 0x0, 0x0)
	/go/src/github.com/openshift/openshift-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:227 +0x8a
github.com/openshift/openshift-azure/vendor/k8s.io/apimachinery/pkg/util/wait.Poll(0x77359400, 0x1176592e000, 0xc000413890, 0x12, 0xc000413890)
	/go/src/github.com/openshift/openshift-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:221 +0x4d
github.com/openshift/openshift-azure/test/e2e/specs/fakerp.glob..func1.5()
	/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/admin.go:67 +0xa1
github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc0001849c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113 +0x9c
github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc0001849c0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0x12c
github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc0001864e0, 0x1402300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/leafnodes/it_node.go:26 +0x7f
github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc00037c2d0, 0x0, 0x1402300, 0xc00004ad80)
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:203 +0x636
github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc00037c2d0, 0x1402300, 0xc00004ad80)
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0xf7
github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc0003f0280, 0xc00037c2d0, 0x0)
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x10f
github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc0003f0280, 0x1)
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x328
github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc0003f0280, 0x9)
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:66 +0x11f
github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0000e0280, 0x7f8ee3041170, 0xc00017eb00, 0x12a9857, 0x9, 0xc0004f28b0, 0x1, 0x1, 0x141f420, 0xc00004ad80, ...)
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:62 +0x28f
github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x1402e20, 0xc00017eb00, 0x12a9857, 0x9, 0xc00007df28, 0x1, 0x1, 0x6)
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:221 +0x247
github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo.RunSpecs(0x1402e20, 0xc00017eb00, 0x12a9857, 0x9, 0x1)
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:202 +0x89
github.com/openshift/openshift-azure/test/e2e.TestE2E(0xc00017eb00)
	/go/src/github.com/openshift/openshift-azure/test/e2e/e2e_test.go:28 +0xd9
testing.tRunner(0xc00017eb00, 0x1335028)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x353

goroutine 13 [chan receive, 20 minutes]:
github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).registerForInterrupts(0xc0003f0280, 0xc0004ee960)
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:223 +0xd1
created by github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:60 +0x8b

goroutine 70 [IO wait]:
internal/poll.runtime_pollWait(0x7f8ee3038f00, 0x72, 0xc00007d868)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00032f598, 0x72, 0xffffffffffffff00, 0x1403bc0, 0x1ea65c0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00032f598, 0xc0003a6000, 0x2000, 0x2000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00032f580, 0xc0003a6000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00032f580, 0xc0003a6000, 0x2000, 0x2000, 0x40a7cb, 0xc000030000, 0x116e920)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e050, 0xc0003a6000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc0003986c0, 0x14028c0, 0xc00000e050, 0x5, 0xc00000e050, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc0004d4380, 0x1336f17, 0xc0004d44a0, 0x1)
	/usr/local/go/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).Read(0xc0004d4380, 0xc00020f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1145 +0xf1
bufio.(*Reader).Read(0xc0001847e0, 0xc00058c2d8, 0x9, 0x9, 0xc000504a78, 0xc000240c20, 0xc00007dd08)
	/usr/local/go/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0x14013e0, 0xc0001847e0, 0xc00058c2d8, 0x9, 0x9, 0x9, 0xc00007dcd8, 0x407df4, 0xc000504a20)
	/usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(0x14013e0, 0xc0001847e0, 0xc00058c2d8, 0x9, 0x9, 0xc00007dd08, 0xc000000401, 0xc00036d500)
	/usr/local/go/src/io/io.go:329 +0x58
github.com/openshift/openshift-azure/vendor/golang.org/x/net/http2.readFrameHeader(0xc00058c2d8, 0x9, 0x9, 0x14013e0, 0xc0001847e0, 0x0, 0x0, 0xc00007dfb0, 0xc0006aa000)
	/go/src/github.com/openshift/openshift-azure/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/openshift/openshift-azure/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc00058c2a0, 0xc000412900, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/openshift-azure/vendor/golang.org/x/net/http2/frame.go:492 +0xa3
github.com/openshift/openshift-azure/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00007dfb0, 0x1336090, 0xc000069fb0)
	/go/src/github.com/openshift/openshift-azure/vendor/golang.org/x/net/http2/transport.go:1428 +0x9c
github.com/openshift/openshift-azure/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc00056a000)
	/go/src/github.com/openshift/openshift-azure/vendor/golang.org/x/net/http2/transport.go:1354 +0x83
created by github.com/openshift/openshift-azure/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/go/src/github.com/openshift/openshift-azure/vendor/golang.org/x/net/http2/transport.go:579 +0x602

goroutine 20 [select]:
github.com/openshift/openshift-azure/vendor/k8s.io/apimachinery/pkg/util/wait.poller.func1.1(0xc0004ee1e0, 0x77359400, 0x1176592e000, 0xc0004ee120)
	/go/src/github.com/openshift/openshift-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:354 +0x153
created by github.com/openshift/openshift-azure/vendor/k8s.io/apimachinery/pkg/util/wait.poller.func1
	/go/src/github.com/openshift/openshift-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:337 +0x8c
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/849/pull-ci-openshift-openshift-azure-master-e2e-azure/1215
/kind test-flake
/area tests

**Comment by mjudeikis** [comment] 2018-12-07 15:01
Its there:
```
kube-state-metrics-64cc8b86b5-5h7gk            3/3       Running   0          2m
[root@master-000000 ~]# oc get deploymebt
error: the server doesn't have a resource type "deploymebt"
[root@master-000000 ~]# oc get deployment
NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
cluster-monitoring-operator   1         1         1            1           19m
grafana                       1         1         1            1           13m
kube-state-metrics            1         1         1            1           3m
prometheus-operator           1         1         1            1           14m
```
Confused...

**Comment by mjudeikis** [comment] 2018-12-07 15:10
I suspect this might be operator issue so it does not deploy kube-state-metrics. need more data.

**Comment by kargakis** [comment] 2018-12-12 12:47
Yeah, another one
```
$ oc get deploy
NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
cluster-monitoring-operator   1         1         1            1           16m
grafana                       1         1         1            1           11m
kube-state-metrics            1         1         1            1           1m
prometheus-operator           1         1         1            1           12m
```
It seems it can take up to 10m for the kube-state-metrics deployment to get created.

**Comment by kargakis** [comment] 2018-12-12 12:57
@openshift/sig-monitoring fyi

**Comment by kargakis** [comment] 2018-12-12 13:43
In the following example, it wasn't even created after almost half an hour.
```
openshift-monitoring               cluster-monitoring-operator   1         1         1            1           26m       cluster-monitoring-operator   registry.access.redhat.com/openshift3/ose-cluster-monitoring-operator:v3.11.43                                app=cluster-monitoring-operator
openshift-monitoring               grafana                       1         1         1            1           22m       grafana,grafana-proxy         registry.access.redhat.com/openshift3/grafana:v3.11,registry.access.redhat.com/openshift3/oauth-proxy:v3.11   app=grafana
openshift-monitoring               prometheus-operator           1         1         1            1           23m       prometheus-operator           registry.access.redhat.com/openshift3/ose-prometheus-operator:v3.11                                           k8s-app=prometheus-operator
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/831/pull-ci-openshift-openshift-azure-master-e2e-azure/1355

**Comment by metalmatze** [comment] 2018-12-12 13:48
This is strange, especially as there are no Prometheus and Alertmanager Pods. These should be running before kube-state-metrics gets even reconciled. Compare with these tasks that are run in the order specified: https://github.com/openshift/cluster-monitoring-operator/blob/1322e56e961511994a4a1a5ef55152d3b389575c/pkg/operator/operator.go#L243-L252

Can you check if the Prometheus and Alertmanager StatefulSets are created? 
Additionally @s-urbaniak fixed a bug in Prometheus Operator v0.26, can you check which version of that is running?
Thanks

**Comment by kargakis** [comment] 2018-12-12 13:52
The prometheus and alert manager pods are there
```
openshift-monitoring                alertmanager-main-0                            3/3       Running   0          19m       10.131.0.10   infra-000001
openshift-monitoring                alertmanager-main-1                            3/3       Running   0          18m       10.131.0.11   infra-000001
openshift-monitoring                alertmanager-main-2                            3/3       Running   0          18m       10.131.0.12   infra-000001
openshift-monitoring                cluster-monitoring-operator-755d7848d4-wxn8x   1/1       Running   0          26m       10.131.0.2    infra-000001
openshift-monitoring                grafana-8497b48bd5-qjl45                       2/2       Running   0          22m       10.131.0.7    infra-000001
openshift-monitoring                node-exporter-2spv7                            2/2       Running   0          16m       10.0.0.7      master-000000
openshift-monitoring                node-exporter-9n9x4                            2/2       Running   0          16m       10.0.0.6      compute-000000
openshift-monitoring                node-exporter-bxpth                            2/2       Running   0          16m       10.0.0.8      master-000001
openshift-monitoring                node-exporter-cdnfl                            2/2       Running   0          16m       10.0.0.5      infra-000001
openshift-monitoring                node-exporter-x6pzq                            2/2       Running   0          16m       10.0.0.9      master-000002
openshift-monitoring                prometheus-k8s-0                               4/4       Running   1          21m       10.131.0.8    infra-000001
openshift-monitoring                prometheus-k8s-1                               4/4       Running   1          20m       10.131.0.9    infra-000001
openshift-monitoring                prometheus-operator-5677fb6f87-j9dkr           1/1       Running   0          23m       10.131.0.6    infra-000001
```
```
openshift-monitoring   alertmanager-main        3         3         19m       alertmanager,config-reloader,alertmanager-proxy                                   registry.access.redhat.com/openshift3/prometheus-alertmanager:v3.11,registry.access.redhat.com/openshift3/ose-configmap-reloader:v3.11,registry.access.redhat.com/openshift3/oauth-proxy:v3.11
openshift-monitoring   prometheus-k8s           2         2         21m       prometheus,prometheus-config-reloader,prometheus-proxy,rules-configmap-reloader   registry.access.redhat.com/openshift3/prometheus:v3.11,registry.access.redhat.com/openshift3/ose-prometheus-config-reloader:v3.11,registry.access.redhat.com/openshift3/oauth-proxy:v3.11,registry.access.redhat.com/openshift3/ose-configmap-reloader:v3.11
```
It's only kube-state-metrics that is flaky.

**Comment by s-urbaniak** [comment] 2018-12-12 13:58
@kargakis I see you have 3.11 images `registry.access.redhat.com/openshift3/ose-prometheus-operator:v3.11`. That's strange as the bug I fixed began to be visible for openshift >=4.0. Nevertheless can you "kick" aka `kubectl delete` the prometheus operator pod?

If it spins up prometheus instances we have a regression in 3.11.

**Comment by kargakis** [comment] 2018-12-12 14:04
@s-urbaniak unfortunately these artifacts are from a test cluster created by our CI that has been cleaned up already. Any pod logs from any of these components that would be useful to you? I can ensure we place them in artifacts in subsequent test runs.

**Comment by s-urbaniak** [comment] 2018-12-12 14:44
@kargakis if you have the chance to grab the prometheus operator logs, that'd be great. at least we would see that it is not sync'ing on the k8s Prometheus custom resource in its logs.

**Comment by kargakis** [comment] 2018-12-12 14:52
@s-urbaniak cool, added log gathering from the prom operator in https://github.com/openshift/release/pull/2366. Will keep you posted on the next failure.

**Comment by kargakis** [comment] 2018-12-13 11:33
> The problem seems to be that the prometheus operator creates the prometheus and alert manager pods one by one, because by default the OrderedReady podManagementPolicy is used in the statefulsets. So we have to wait for 5 pods that use persistent storage to come up serially before we can create the kube-state-metrics deployment.

Opened https://github.com/openshift/cluster-monitoring-operator/pull/184

**Comment by kargakis** [comment] 2018-12-17 10:23
Unfortunately, this still seems to be an issue even after fixing the order with which we healthcheck the monitoring stack.
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/917/pull-ci-openshift-openshift-azure-master-e2e-azure/1424
In this case, [kube-state-metrics was never created](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/917/pull-ci-openshift-openshift-azure-master-e2e-azure/1424/artifacts/e2e-azure/deployments). Can't find anything interesting in the [prometheus-operator log](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/917/pull-ci-openshift-openshift-azure-master-e2e-azure/1424/artifacts/e2e-azure/prometheus-operator.log).

**Comment by s-urbaniak** [comment] 2018-12-17 10:39
In that case the race we fixed in 0.26 might be manifesting here: https://github.com/coreos/prometheus-operator/pull/2177. Before the client generation bump in https://github.com/coreos/prometheus-operator/pull/2163 we didn't see the panic at all, just a deadlocked prometheus operator which seems to be the same sympton as here.

@kargakis by any chance, do you have the possibility to grab the goroutine dump from the running prometheus operator? Something like this:

```
kubectl exec prometheus-operator-565894d646-wrxbd wget -- -O - localhost:8080/debug/pprof/goroutine?debug=2
```

**Comment by squat** [comment] 2018-12-17 11:10
@kargakis i recall you mentionI got something about this being specific to 3.11, no?

**Comment by kargakis** [comment] 2018-12-17 12:34
> @kargakis i recall you mentionI got something about this being specific to 3.11, no? I ask because if this is the case, then the last comment concerning release 0.26.0 of the operator does not apply here, as the bug was not introduced until openshift 4.0. If not, please disregard this comment.

OSA is still 3.11, the prometheus operator image used is `registry.access.redhat.com/openshift3/ose-prometheus-operator:v3.11`.

**Comment by squat** [comment] 2018-12-17 12:39
> OSA is still 3.11, the prometheus operator image used is

Ack, that’s what I remember. As mentioned, the recent change to the prometheus operator are not relevant as the race it targetted was not present in the 0.23.2, the version in 3.11.

**Comment by kargakis** [comment] 2018-12-17 12:47
@s-urbaniak @squat do you still need me to get the goroutine dump?

**Comment by s-urbaniak** [comment] 2019-01-02 12:04
@kargakis ok, it seems the prometheus operator seems fine, both from the logs and the goroutine dump. The place it is stuck, is determining a successful rollout of node exporter pods and getting past it, which is strange because node exporter does seem to be deployed :thinking: I couldn't seem to find cluster monitoring operator logs in the artifacts. Can you extract those?

**Comment by kargakis** [comment] 2019-01-02 12:31
Opened https://github.com/openshift/release/pull/2479 to gather the cluster monitoring operator log in the test artifacts.

**Comment by mjudeikis** [comment] 2019-01-02 15:08
Just had the similar use case where kube-state-metrics was not there in my local testing. Managed to get logs just before cluster was deleted: 
https://gist.github.com/mjudeikis/0a9e1bc38a2007841ecdfeee5035f0be

**Comment by s-urbaniak** [comment] 2019-01-02 17:57
@mjudeikis awesome, thanks! :+1: this gives just a little bit more context. Indeed cluster monitoring operator is stuck at reconciling the node-exporter daemonset, getting this error from the API server:
```
E0102 14:50:03.680816       1 operator.go:207] sync "openshift-monitoring/cluster-monitoring-config" failed: running task Updating node-exporter failed: reconciling node-exporter DaemonSet failed: updating DaemonSet object failed: timed out waiting for the condition
```

I saw in the events quite some network hickups, Is the Azure network stable? Do you see any other operators seeing timeouts when communicating with the API server?

**Comment by mjudeikis** [comment] 2019-01-03 09:18
@s-urbaniak its 3.11 so its first operator running here. And most of the heavy lifting API server processes are running on the masters itself than this one is on Infra nodes. And I dont think I recall DS being created at all.

**Comment by mjudeikis** [comment] 2019-02-18 11:11
Wondering when was the last time we have seen this?

**Comment by jim-minter** [comment] 2019-03-15 16:08
not seen recently, reopen if needed

**Closed by jim-minter** 2019-03-15 16:08 UTC
Labels: area/tests, kind/test-flake
