### ISSUE TITLE
e2e tests are failing with stat ../../_data/_out/admin.kubeconfig: no such file or directory

### ISSUE THREAD

**Issue by asalkeld** [openshift/openshift-azure#529] opened 2018-09-28 07:34 UTC
Failure [0.001 seconds]
[BeforeSuite] BeforeSuite
/go/src/github.com/openshift/openshift-azure/test/e2e/osa_test.go:25

  Expected error:
      <*os.PathError | 0xc4203a8000>: {
          Op: "stat",
          Path: "../../_data/_out/admin.kubeconfig",
          Err: 0x2,
      }
      stat ../../_data/_out/admin.kubeconfig: no such file or directory
  not to have occurred

  /go/src/github.com/openshift/openshift-azure/test/e2e/osa_test.go:29
------------------------------

Ran 2 of 0 Specs in 0.001 seconds
FAIL! -- 0 Passed | 2 Failed | 0 Pending | 0 Skipped
--- FAIL: TestExtended (0.00s)

**Comment by mjudeikis** [comment] 2018-09-28 07:43
as per this it should work:
https://github.com/openshift/release/blob/master/ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml#L103-L105 

hmmm. checking if its a flake or we miss some path in template

**Comment by mjudeikis** [comment] 2018-09-28 13:30
duplicate of: https://github.com/openshift/openshift-azure/issues/530 
/close

**Closed by mjudeikis** 2018-09-28 13:30 UTC
