### ISSUE TITLE
Scale operation fails during VM Extension run: "failed to execute command"

### ISSUE THREAD

**Issue by amanohar** [openshift/openshift-azure#708] opened 2018-11-08 02:55 UTC
Scale operation fails during VM Extension run: "failed to execute command".

Two occurrences of this error both in Australia East (during scale up operation).

> {
>   "code": "VMExtensionProvisioningError",
>   "message": "VM has reported a failure when processing extension 'cse'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1[stdout]meta-data=/dev/disk/azure/resource-part1 isize=512    agcount=4, agsize=1048508 blks         =                       sectsz=4096  attr=2, projid32bit=1         =                       crc=1        finobt=0, sparse=0data     =                       bsize=4096   blocks=4194032, imaxpct=25         =                       sunit=0      swidth=0 blksnaming   =version 2              bsize=4096   ascii-ci=0 ftype=1log      =internal log           bsize=4096   blocks=2560, version=2         =                       sectsz=4096  sunit=1 blks, lazy-count=1realtime =none                   extsz=4096   blocks=0, rtextents=0[stderr]+ SERVICE_TYPE=origin+ '[' -f /etc/sysconfig/atomic-openshift-node ']'+ SERVICE_TYPE=atomic-openshift+ grep /var/lib/docker /etc/fstab+ mkfs.xfs -f /dev/disk/azure/resource-part1+ echo '/dev/disk/azure/resource-part1  /var/lib/docker  xfs  grpquota  0 0'+ systemctl stop docker.serviceJob for docker.service canceled.\"."
> }

**Comment by kargakis** [comment] 2018-11-08 10:40
Seems to be the same as https://github.com/openshift/openshift-azure/issues/600

/kind bug

**Comment by kwoodson** [comment] 2018-11-29 20:02
According to this bug and #600 I'm not sure exactly which command is failing.  It looks like the docker operation timed out attempting to stop.

https://github.com/openshift/openshift-azure/blob/master/pkg/arm/data/node-startup.sh#L15
```
systemctl stop docker.service\\nJob for docker.service canceled.
```

There are a few options we can take here.  We can start the image with docker stopped until the formatting of the docker drive has completed.  This would eliminate one of the startup steps.

I'd like to get more debug information from this in order to narrow down the cause.

**Comment by kargakis** [comment] 2019-01-10 13:16
Latest failure: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1015/pull-ci-openshift-openshift-azure-master-e2e-azure/1816

@kwoodson what info would you be interested in seeing?

**Comment by kwoodson** [comment] 2019-01-10 14:53
It looks like this is what is failing:
https://github.com/openshift/openshift-azure/blob/master/pkg/arm/data/node-startup.sh#L15

I'd like to know what docker is doing.  Maybe:
- `ps -ef | grep docker`
- `docker info`
- `fdisk -l` or `cat /proc/partition` - see the state of the partition table
- dump the docker journal (journal -xe)
- systemctl status docker

My guess is some docker is initializing storage.  We could also get more aggressive and attempt to stop docker.  If it doesn't stop then proceed to `kill -9` in an attempt to make it more resilient.

Another suggestion is to reinitialize the docker storage.  Since this is a first time boot so we can rm -rf /var/lib/docker.  This seems to have fixed 

@kargakis wdyt?

Also, what's the best way to reproduce?  Continually run the upgrade? Scale up/down continuously?

**Comment by jim-minter** [comment] 2019-03-05 16:07
Closing for AZURE-297

**Closed by jim-minter** 2019-03-05 16:07 UTC
Labels: ga, kind/bug, kind/test-flake
