### ISSUE TITLE
scale-up-down nodes cleaning

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#252] opened 2018-08-23 18:49 UTC
If you scale up and down node scaleset, old nodes are not cleaned :) 

```
[mangirdas@unknown openshift-azure]$ oc get nodes
NAME             STATUS     ROLES     AGE       VERSION
compute-000000   Ready      compute   1h        v1.10.0+b81c8f8
compute-000001   NotReady   compute   22m       v1.10.0+b81c8f8
compute-000002   NotReady   compute   22m       v1.10.0+b81c8f8
compute-000003   NotReady   compute   22m       v1.10.0+b81c8f8
compute-000004   NotReady   compute   22m       v1.10.0+b81c8f8
compute-000005   NotReady   compute   22m       v1.10.0+b81c8f8
infra-000000     Ready      infra     1h        v1.10.0+b81c8f8
master-000000    Ready      master    1h        v1.10.0+b81c8f8
master-000001    Ready      master    1h        v1.10.0+b81c8f8
master-000002    Ready      master    1h        v1.10.0+b81c8f8

```

**Comment by kargakis** [comment] 2018-08-30 11:06
Closing as a dupe of https://github.com/openshift/openshift-azure/issues/285

**Closed by kargakis** 2018-08-30 11:06 UTC
Labels: kind/bug
