### ISSUE TITLE
SRE e2e tests fail in verifying that kube-state-metrics started correctly

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#865] opened 2018-12-07 14:53 UTC
The SRE (azure cluster reader) e2e test suite is currently failing during the test which checks that `kube-state-metrics` is started correctly

```
------------------------------
Openshift on Azure admin e2e tests [AzureClusterReader] 
  should start kube-state-metrics correctly
  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/admin.go:66
panic: test timed out after 20m0s

goroutine 623 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1296 +0xfd
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44

```

https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/794/pull-ci-openshift-openshift-azure-master-e2e-azure/1268/

/kind bug
/cc @mjudeikis

**Comment by mjudeikis** [comment] 2018-12-07 14:55
The fun thing that kube-state metrics is part of the operator :/ https://github.com/openshift/openshift-azure/blob/9c94dda629d72ad08586fd7a758cc166294f7985/pkg/addons/data/ConfigMap/openshift-monitoring/cluster-monitoring-config.yaml#L48

**Comment by kargakis** [comment] 2018-12-07 14:59
dupe of https://github.com/openshift/openshift-azure/issues/850

**Closed by kargakis** 2018-12-07 14:59 UTC
Labels: kind/bug
